Linters applied and run
Svartstein/final-capstone pull request #16
Opened 2023-10-05 17:27 UTC by Swarzstein

## In this Pull Request:

1. The user logs in to the website, only by typing the username.
2. In the navigation panel, the user can see links to:
   - Trip Packages.
   - "Reserve" form.
   - "My reservations".
   - "Add Trip Package.
   - "Delete Trip Package.
3. On the main page, the user can see a list of Trip Packages.
4. When the user selects a specific item, they can see the details page with its full description.
   - On the details page, the user can click the "Reserve" button (with no functionality as we are 2).

2023-10-05 19:19 UTC, Meltrust commented on .github/workflows/linters.yml
> +name: Linters
- [ ] There is no functional readme file.  Go to this [repo](https://github.com/microverseinc/readme-template), grab the README.md template there, and customize it for your project.

Remember, your readme needs to have specific instructions about how to setup and run your project, as well as your tests.  👍

2023-10-05 19:19 UTC, Meltrust commented on .github/workflows/linters.yml
> +
- [ ] The frontend styling is vastly different from the required design:

![image](https://github.com/Swarzstein/final-capstone/assets/57421823/9b326572-4e8e-4e53-bf42-55bf5afa0540)

![image](https://github.com/Swarzstein/final-capstone/assets/57421823/043240b3-5000-4869-8b37-15b3a2c31783)


Kindly, add the required styling to make it look like in the required design. 👍 

- [ ] As you commented in your description, there is no mobile version yet.

- [ ] As you commented in your description, there is no adding items functionality yet.

- [ ] Remember:  Reservations and deletions are not a requirement for a group of 2 people.  However, if you implement them, they need to work well. 👍

2023-10-05 19:19 UTC, Meltrust commented on .github/workflows/linters.yml
> +name: Linters
- [ ]  Please, kindly refactor this and all other functions in your project to ES6 arrow functions, so your code complies with the latest standards.

Refactoring is easy:

```javascript
const App = () => {
  // ...
}
```

## Explanation

The `function` keyword has been soft deprecated in almost all the software industry in favor of ES6 arrow functions. This means, almost nobody uses it anymore, so much that it's considered a non-best practice.

You can do a search in Vscode for the "function" word, and correct as needed.  Shouldn't take you more than 5-10 min so don't worry (I found 7):  

![image](https://github.com/Swarzstein/final-capstone/assets/57421823/2dfb1382-9526-4bf7-bd19-691fe3a236a0)


![image](https://github.com/Swarzstein/final-capstone/assets/57421823/020c9792-25b8-4dfd-a1f1-e2c462f0c96a)


That way, your code will meet the latest standards. 💪

2023-10-05 19:19 UTC, Meltrust commented on .github/workflows/linters.yml
> +name: Linters
- [ ] Kindly, remove this console.log debugging statements present in these files:

![image](https://github.com/Swarzstein/final-capstone/assets/57421823/07320298-7474-4778-9acd-79aca86fc11f)

That way, the repo will be cleaner. 👍

2023-10-05 19:23 UTC, Meltrust requested changes
Hi @Swarzstein,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!










#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-10-05 19:23 UTC, Meltrust commented on .github/workflows/linters.yml
> +name: Linters
- [ ] Please, remove the old commented code found in:

- Details.js
- Item.js

2023-10-05 19:23 UTC, Meltrust commented on .github/workflows/linters.yml
> +name: Linters
- [ ] What happens here if the trip is not successfully destroyed?  Add some error handling:

![image](https://github.com/Swarzstein/final-capstone/assets/57421823/c38d1da1-762a-4291-8e16-27913670acf4)

2023-10-06 05:42 UTC, merged

2023-10-06 09:58 UTC, mcrd25 reviewed
Hi @Swarzstein,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Good try with changes 👍 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- Don't forget that the application needs to look exactly like design with exception of photos, titles and descriptions - Still ahve a bit to go with with but good job so far 👍 
- you are missing documentation. Consider using the `rswag` gem : https://github.com/rswag/rswag
  You may also use: 
   - swagger-docs: https://github.com/richhollis/swagger-docs
   - swagger-ui_rails2: https://github.com/ryansyl/swagger_ui_rails2
- I don't see front-end or back-end tests, I'd add some comments for you to consider if you do implement
- For Back-End tests use rspec: https://rspec.info/
- [OPTIONAL] removing the `test` directory since you are using `rspec` for testing and not native testing. [(BACKEND)
- [OPTIONAL] Consider using the `timecop` gem to freeze time when running tests. It can help avoid errors: https://github.com/travisjeffery/timecop (BACKEND)
*  I am not seeing tests for your Front-End code - this is something we expect to be implemented for the final evaluation. Here are some resources you can use:
   *  https://reactjs.org/docs/testing.html
   * https://jestjs.io/docs/tutorial-react
   * https://www.freecodecamp.org/news/testing-react-hooks/
- There are some candidates to make some of these html components reusable. [OPTIONAL] - using sub-components, arrays and mapping functions
- Seeing where you can make code better by following best practices: See the following articles
   - https://www.freecodecamp.org/news/best-practices-for-react/
   - https://betterprogramming.pub/21-best-practices-for-a-clean-react-project-df788a682fb

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

**Hope all is well, and that my comments were helpful. 😸**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
_Also, you do not have to implement all requested changes, as this is up to you in the end, but I strongly recommend you implement them._